### ISSUE TITLE
Does not logout on invalid token - was: Modifica non funziona

### ISSUE THREAD

**Issue by opensamba** [lesion/gancio#2]
Se provo a modificare un evento, per esempio la descrizione e poi faccio continua > modifica non esco dal menu. Rimango fisso su Modifica senza la possibilita' di modificare l'evento

**Comment by opensamba** [comment]
forse e' relativo al fatto che non ho la Locandina. 

Locandina e' l'ultimo passaggio e io non avendo l'immagina (voglio semplicamente fare modifica di una descrizione) premo Modifica ma non riesco ad uscire.

**Comment by lesion** [comment]
il problema e' un altro, non hai piu' l'utente e non capisce che il tuo token non esiste piu' (cioe' non te lo dice piu' che altro con un errore, sloggandoti)
